### ISSUE TITLE
Upload to Modrinth/CurseForge

### ISSUE THREAD

**Issue by RaptaG** [theRookieCoder/StairAutoJump#3]
The mod will become more popular and reach more people! It could also be included in modpacks if uploaded to these websites

**Comment by theRookieCoder** [comment]
To be honest, this mod is so simple I didn't really expect anyone would use it. I guess I'll just upload it any ways, it's not that hard to do.

**Comment by theRookieCoder** [comment]
Modrinth and CurseForge projects are waiting for approval. Also I had to use an AI upscaler because CF wants mod icons to be a minimum of 400x

**Comment by RaptaG** [comment]
> Also I had to use an AI upscaler because CF wants mod icons to be a minimum of 400x

CurseForge moment :skull:

**Comment by theRookieCoder** [comment]
Modrinth project has been approved

**Comment by RaptaG** [comment]
> Modrinth project has been approved

1. No 0.0.3 on GH releases :(

2. Why beta?

![](https://user-images.githubusercontent.com/77157639/174455425-47916af2-2247-4ecf-b684-d0d420e7781e.jpeg)

**Comment by RaptaG** [comment]
Also make sure to update the README in the Modrinth and the CurseForge page when approved

**Comment by theRookieCoder** [comment]
1. Oops I'd forgotten, I've just created the release
2. There are still some features I'd like to implement, and it hasn't been extensively tested with other mods

I already updated the readme before the projects got approved

**Comment by RaptaG** [comment]
Ok, approved everywhere, I'm closing this now...

**Comment by RaptaG** [comment]
This is kinda outdated:
![image](https://user-images.githubusercontent.com/77157639/174500865-731bb54d-9786-4174-aaa7-2b5ae9afea5d.jpeg)
